import { Flipkart_type } from "src/app/flipkart_type"

export const Fipkart_data_object : Flipkart_type[] = [
    {
        "id" : 1,
        "image_src" : "./res/linen.webp",
        "pname" : "Trance Home Linen Fitted Single Size Waterproof Mattress Cover  (Brown)",
        "pcolor" : "Brown",
        "stars" : 4.2,
        "hashReview" : 2271,
        "price" : 682.0,
        "originalPrice" : 1399.0,
        "discount" : 51,
        "brand" : "Trance",
        "category" : "Home Linen",
        "latest" : true
    },
    {
        "id" : 2,
        "image_src" : "./resouces/window_curtain.webp",
        "pname" : "RSTC 152 cm (5 ft) Net Semi Transparent Window Curtain (Pack Of 2)  (3D Printed, White)",
        "pcolor" : "White",
        "stars" : 4.3,
        "hashReview" : 6067,
        "price" : 334.0,
        "originalPrice" : 1599.0,
        "discount" : 79,
        "brand" : "RSTC",
        "category" : "Home Linen",
        "latest" : false
    },
    {
        "id" : 3,
        "image_src" : "./resouces/refrigirator_cover.webp",
        "pname" : "Kanushi Industries Refrigerator Cover  (Width: 91 cm, Brown)",
        "pcolor" : "Brown",
        "stars" : 4,
        "hashReview" : 32179,
        "price" : 158.0,
        "originalPrice" : 499.0,
        "discount" : 68,
        "brand" : "Kanushi",
        "category" : "Home Linen",
        "latest" : true
    },
    {
        "id" : 4,
        "image_src" : "./resouces/floor_mat.webp",
        "pname" : "varsha tex Cotton Floor Mat  (Multicolor, Medium, Pack of 5)",
        "pcolor" : "Muliticolor",
        "stars" : 3.6,
        "hashReview" : 4078,
        "price" : 194.0,
        "originalPrice" : 999.0,
        "discount" : 80,
        "brand" : "varsha",
        "category" : "Home Linen",
        "latest" : true
    },
    {
        "id" : 5,
        "image_src" : "./resouces/boat_speaker.webp",
        "pname" : "boAt Stone 350 10 W Bluetooth Speaker  (Black, Mono Channel)",
        "pcolor" : "Black",
        "stars" : 4.3,
        "hashReview" : 61551,
        "price" : 1599.0,
        "originalPrice" : 3490.0,
        "discount" : 54,
        "brand" : "boAt",
        "category" : "Electronics",
        "latest" : true
    },
    {
        "id" : 6,
        "image_src" : "./resouces/boult_earphone.webp",
        "pname" : "Boult Audio ProBass Curve Neckband Bluetooth Headset  (Black, Grey, In the Ear)",
        "pcolor" : "Black , Grey",
        "stars" : 4,
        "hashReview" : 42989,
        "price" : 899.0,
        "originalPrice" : 3499.0,
        "discount" : 74,
        "brand" : "Boult",
        "category" : "Electronics",
        "latest" : false
    },
    {
        "id" : 7,
        "image_src" : "./resouces/LG_TV1.webp",
        "pname" : "LG 164 cm (65 inch) Ultra HD (4K) LED Smart WebOS TV  (65UP7500PTZ)",
        "pcolor" : "Black",
        "stars" : 4.4,
        "hashReview" : 5879,
        "price" : 74990.0,
        "originalPrice" : 119990.0,
        "discount" : 37,
        "brand" : "LG",
        "category" : "Appliances",
        "latest" : false
    },
    {
        "id" : 8,
        "image_src" : "./resouces/LG_TV2.webp",
        "pname" : "LG Nanocell 139 cm (55 inch) Ultra HD (4K) LED Smart WebOS TV  (55NANO73TPZ)",
        "pcolor" : "Black",
        "stars" : 4.4,
        "hashReview" : 374,
        "price" : 59990.0,
        "originalPrice" : 109990.0,
        "discount" : 45,
        "brand" : "LG",
        "category" : "Appliances",
        "latest" : true
    },
    {
        "id" : 9,
        "image_src" : "./resouces/creta_shoes.webp",
        "pname" : "Creta-12 sports shoes for men",
        "pcolor" : "White",
        "stars" : 4,
        "hashReview" : 13268,
        "price" : 718.0,
        "originalPrice" : 1299.0,
        "discount" : 44,
        "brand" : "Asian",
        "category" : "Shoes",
        "latest" : false
    }
]